/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Experience: typeof import('./src/components/experience.vue')['default']
    Me: typeof import('./src/components/me.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    Projects: typeof import('./src/components/projects.vue')['default']
  }
}
